name: Build NMiner

on:
  push:
    branches: [ master ]

jobs:
  ubuntu:
    timeout-minutes: 15
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-20.04 }
          - { os: ubuntu-22.04 }

    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

          sudo apt update
          sudo apt install -y git build-essential cmake python3 nodejs npm

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install NPM dependencies
        run: |
          npm install --ignore-scripts

      - name: Build NMiner
        run: |
          mkdir -p build && npm run build