name: Build NMiner

on:
  push:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-22.04, name: linux }
          - { os: windows-latest, name: win32 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - if: matrix.config.name == 'linux'
        name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake python3

      - if: matrix.config.name == 'win32'
        name: Install Windows dependencies
        uses: microsoft/setup-msbuild@v3
      
      - name: Install & Build
        run: |
          npm install --ignore-scripts

          mkdir -p build && npm run build
      
      - if: matrix.config.name == 'linux'
        name: Strip Symbols
        run: |
          strip --strip-all build/Release/NMiner.node
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: addon-${{ matrix.config.name }}
          path: build/Release/NMiner.node

  publish:
    name: Publish & Release
    needs: build
    runs-on: ubuntu-latest
    
    if: startsWith(github.event.commits[0].message, 'Release:')
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org

      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          path: ./temp
        
      - name: Prepare Package
        run: |
          mkdir -p bin
          
          cp temp/addon-win32/NMiner.node ./bin/nminer-win32.node
          cp temp/addon-linux/NMiner.node ./bin/nminer-linux.node
          
          zip -r nminer-win32.zip bin/nminer-win32.node src/js/*.js index.js index.d.ts package.json LICENSE
          tar -czvf nminer-linux.tar.gz bin/nminer-linux.node src/js/*.js index.js index.d.ts package.json LICENSE

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.2.13
          name: NMiner v1.2.13
          draft: true
          prerelease: false
          files: |
            nminer-win32.zip
            nminer-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}