name: Build NMiner

on:
  push:
    branches: [ master ]

jobs:
  ubuntu:
    timeout-minutes: 15
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-20.04 }
          - { os: ubuntu-22.04 }
          - { os: ubuntu-24.04 }

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake python3 libnuma-dev
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: |
          npm install --ignore-scripts

      - name: Build NMiner
        run: |
          mkdir -p build && npm run build

      - name: Package NMiner
        run: |
          tar -czvf nminer.tar.gz package.json index.js index.d.ts LICENSE build/Release/NMiner.node src/js/*.js
      
      - name: Upload NMiner
        uses: actions/upload-artifact@v4
        with:
          name: nminer-${{matrix.config.os}}.tar.gz
          path: nminer.tar.gz

  windows:
    timeout-minutes: 20
    runs-on: windows-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install -y cmake python3
        
      - name: Install dependencies
        run: |
          choco install -y cmake python3

      - name: Build NMiner
        run: |
          mkdir -p build && npm run build