name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-ubuntu:
    timeout-minutes: 15
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - { os: ubuntu-20.04, c: gcc-11, cpp: g++-11 }

    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y git build-essential cmake ${{ matrix.config.c }} ${{ matrix.config.cpp }} python3 nodejs npm

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build RandomX
        run: |
          mkdir -p build_randomx
          cd build_randomx
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          cd ..